# Inmobiler JP modules config

## App
[app]
  ddbb = "sqli"

## Protocols
[ProposalDTO]
  mandatory = ["documents", "offerentID", "demandID", "proposed_validity_days", "currency", "offering"]

[ABSofferingDTO]
  mandatory = ["offertID"]

[ServiceOfferingDTO]
  mandatory = ["date", "location", "budget", "advance_payment"]

[RentOfferingDTO]
  mandatory = ["start_date", "end_date", "starting_value", "variable_fee", "guarantee_deposit", "deposit_as_percent_total_rent"]
